# Lecture 4: Measures of Central Tendency

## Scenario: Crime in Slumberg

The city of **Slumberg** is studying burglary patterns across neighborhoods. They are interested in answering these questions:

- What is the most common neighborhood for burglaries?
- What is the typical level of fear of crime?
- What is the average response time for burglary calls?

The police department collected data on 10 recent burglary cases. The data are:

<!-- make table smaller -->
\small

| Case | Neighborhood | Response Time (min) | Value Stolen (\$100s) | Fear of Crime (1–5) |
|------|---------------|--------------------|-----------------------|---------------------|
| 1 | East | 4 | 8 | 4 |
| 2 | East | 5 | 2 | 3 |
| 3 | North | 6 | 3 | 3 |
| 4 | East | 7 | 4 | 4 |
| 5 | West | 6 | 12 | 5 |
| 6 | North | 5 | 3 | 2 |
| 7 | North | 8 | 3 | 4 |
| 8 | West | 10 | 15 | 5 |
| 9 | East | 4 | 1 | 3 |
| 10 | East | 5 | 4 | 3 |
| 11 | East | 6 | 4 | 3 |

\normalsize

### Central Tendency

Different measures of central tendency tell different stories about typical values.

- The *mode* answers questions about what is most common.
- The *median* answers questions about what falls in the middle.
- The *mean* answers questions about overall balance or expected value.

## Research Questions

### Mode – **What is the most common neighborhood for burglaries?**

To find the mode, we count the number of burglaries per neighborhood and make a frequency table:

| Neighborhood | *f* |
|--------------|-------|
| East         | 6 |
| North        | 3 |
| West         | 2 |

What is the modal category? What is the answer to our research question?

### Median – **What is the typical level of fear of crime?**

The median describes the "typical" value by identifying the middle of our values. Why does the middle describe a "typical" value?

To find the *median*, we follow several steps: 
  1. Arrange the values in the data in ascending order
  2. Find the middle value of the ordered data  
    - If <u>odd</u> number of cases, then the *median* is the $(1 + N)/2$ case
    - If <u>even</u> number of cases, then the *median* is between the $N/2$ and $(N/2)+1$ cases

#### Let's take a look at our example

Arrange the values in the data in ascending order. 
Our data values are: 4, 3, 3, 4, 5, 2, 4, 5, 3, 3, 3. 
Then if we put them in ascending order: 2, 3, 3, 3, 3, 3, 4, 4, 4, 5, 5.

Now, we find the middle value of the ordered data. 
There are $N$ = 11 cases, so the median is the $(1 + N)/2=6$ case in the sorted data.  

What is the 6th case? And, what is the interpretation? The typical fear-of-crime level in Slumberg is a 3 (“somewhat afraid”).

What if we only had 10 cases (say our data are: 2, 3, 3, 3, 3, 3, 4, 4, 4, 5)? If even number of cases, then the *median* is between the $N/2$ and $(N/2)+1$ cases. In that case, the median would be between the 5th and 6th case. What is the median?

### Mean – What is the average response time for burglary calls?

The *mean* is the expected value, or average. We will use this formula:

$$
\bar{x} = \frac{\sum_{i=1}^{N} x_i}{N}
$$
Where:

$\bar{x}$ = the mean, 
$x_i$ = each individual observation, 
$\sum$ = "Sigma" (meaning to add), 
and $N$ = total number of observations.

To find the mean, we just work through the equation and substitute our raw data:

$$\bar{x} = \frac{4 + 5 + 6 + 7 + 6 + 5 + 8 + 10 + 4 + 5 + 6}{N} = \frac{66}{N} = \frac{66}{11} = 6$$

On average, police took about 6 minutes to respond to burglary calls.